- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False


  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages/install_slack.yml
    - include: tasks/packages/install_spotify.yml
    - include: tasks/packages/install_hiri.yml
    - include: tasks/packages/install_postman.yml
    - include: tasks/packages/install_vscode.yml
    - include: tasks/packages/install_docker.yml
    - include: tasks/tf-logstash.yml