- name: Initial OS setup
  hosts: localhost
  become: true

  #vars_prompt:
  #  - name: git_user
  #    private: no
  #  - name: git_pass
  #    private: yes

  vars:
    repo_name: tf-home-assistant

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  roles:
    - role: roles.galaxy/gantsign.oh-my-zsh
      users:
        - username: shawn
          plugins:
            - git
    - role: roles.galaxy/andrewrothstein.terraform
    - role: roles.galaxy/andrewrothstein.unarchive-deps

  tasks: 
    - import_tasks: tasks/users.yml
    - import_tasks: tasks/cron.yml
    - import_tasks: tasks/packages/install_dependencies.yml
    - name: Import preinstall_config role
      import_role:
        name: jhampson_dbre.home_assistant.preinstall_config
      vars:
        has_reserved_ip: true

#    - import_tasks: tasks/tf-homeassistant.yml
    - import_tasks: tasks/packages/install_slack.yml
    - import_tasks: tasks/packages/install_spotify.yml
    - import_tasks: tasks/packages/install_postman.yml
    - import_tasks: tasks/packages/install_vscode.yml
#    - import_tasks: tasks/packages/install_docker.yml

# Since preinstall_config creates a non-root account,
# we can use `become: yes` for privelege escalation
# instead of logging in directly as root
- name: Install Home Assistant Supervised and Requirements
  hosts: all
  become: true
  force_handlers: true
  roles:
    - role: roles.galaxy/jhampson_dbre.home_assistant/supervised_install

# Extras
- name: Security Hardening and enhancements
  hosts: all
  become: true
  force_handlers: true
  roles:
    - role: roles.galaxy/jhampson_dbre.home_assistant/harden_os
    - role: roles.galaxy/jhampson_dbre.home_assistant/os_agent_auto_update
    - role: roles.galaxy/jhampson_dbre.home_assistant/fail2ban
      vars:
       fail2ban_reverse_proxy_addon_name: addon_85d0901c_nginx_proxy_waf
    - role: roles.galaxy/jhampson_dbre.home_assistant/install_hacs