- hosts: localhost
  become: true

  #vars_prompt:
  #  - name: git_user
  #    private: no
  #  - name: git_pass
  #    private: yes

  vars:
    repo_name: tf-home-assistant

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: shawn
          plugins:
            - git
    - andrewrothstein.terraform
    - andrewrothstein.unarchive-deps

# Minimal Install
#
# Initial setup connects as root over SSH to create
# a new, non-root account to use going forward.
# After the first run, `ansible_user: root` can be removed
# and the non-root account can be used (e.g. as host_var)
- name: Initial OS setup
  vars:
    ansible_user: root
  become: yes
  tasks:
    - name: Import preinstall_config role
      import_role:
        name: jhampson_dbre.home_assistant.preinstall_config
      vars:
        has_reserved_ip: true
        

    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages/install_dependencies.yml
#    - include: tasks/tf-homeassistant.yml
    - include: tasks/packages/install_slack.yml
    - include: tasks/packages/install_spotify.yml
    - include: tasks/packages/install_postman.yml
    - include: tasks/packages/install_vscode.yml
#    - include: tasks/packages/install_docker.yml
    - include: tasks/packages/install_ha_supervised.yml


