- hosts: localhost
  become: true

  #vars_prompt:
  #  - name: git_user
  #    private: no
  #  - name: git_pass
  #    private: yes

  vars:
    repo_name: tf-home-assistant

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: shawn
          plugins:
            - git
    - andrewrothstein.terraform
    - andrewrothstein.unarchive-deps


  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages/install_dependencies.yml
#    - include: tasks/tf-homeassistant.yml
    - include: tasks/packages/install_slack.yml
    - include: tasks/packages/install_spotify.yml
    - include: tasks/packages/install_postman.yml
    - include: tasks/packages/install_vscode.yml
#    - include: tasks/packages/install_docker.yml
    - include: tasks/packagas/install_ha_supervised.yml


