- src: andrewrothstein.terraform
- src: gantsign.oh-my-zsh
collections:
- name: community.docker
- name: jhampson_dbre.home_assistant.harden_os
- name: jhampson_dbre.home_assistant.fail2ban
- name: jhampson_dbre.home_assistant.install_hacs
- name: jhampson_dbre.home_assistant.os_agent_auto_update