- name: Install roles from Ansible Galaxy
  command: ansible-galaxy install andrewrothstein.terraform
  with_items:
    - "andrewrothstein.terraform"
    
- terraform:
    project_path: '/repos/tf-home-assistant'
    state: present