- git:
    repo: "https://{{git_user|urlencode()}}:{{git_pass|urlencode()}}@github.com/auraShawn/{{repo_name}}.git"
    dest: "/repos/{{repo_name}}"
    update: yes

- name: remove visibility of credentials
  command:
    cmd: git remote set-url origin https://github.com/auraShawn/{{repo_name}}.git

- terraform:
    project_path: '/repos/{{repo_name}}'
    state: present