# Example of using git modle with credentials, will clone if first time and pull latest if exists
# https://github.com/fabianlee/blogcode/blob/master/ansible/playbook-git-withcreds.yml
# Allow prompt for variables or specify in --extra-vars
# ansible-playbook playbook-git-withcreds.yml --extra-vars "git_user=myuser git_pass=Myp4ss!"
#
---
- hosts: localhost
  become: no
  gather_facts: no
  vars_prompt:
    - name: git_user
      private: no
    - name: git_pass
      private: yes

  vars:
    repo_name: tf-home-assistant

  tasks:

  - git:
      repo: "https://{{git_user|urlencode()}}:{{git_pass|urlencode()}}@github.com/auraShawn/{{repo_name}}.git"
      dest: "/repos/{{repo_name}}"
      update: yes

  - name: remove visibility of credentials
    command:
      cmd: git remote set-url origin https://github.com/auraShawn/{{repo_name}}.git

- terraform:
    project_path: '/repos/{{repo_name}}'
    state: present