---
# tasks file for docker-ce-ansible-role

- name: Install docker-ce (RedHat OS family)
  include_tasks: install-EL.yml
  when: ansible_os_family == 'RedHat'

- name: Install docker-ce (Ubuntu)
  include_tasks: install-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Enable Docker CE service on startup
  service:
    name: docker
    state: started
    enabled: yes