---
# Since preinstall_config creates a non-root account,
# we can use `become: yes` for privelege escalation
# instead of logging in directly as root
- name: Install Home Assistant Supervised and Requirements
  hosts: all
  become: yes
  force_handlers: true
  roles:
    - name: jhampson_dbre.home_assistant.supervised_install

# Extras
- name: Security Hardening and enhancements
  hosts: all
  become: yes
  force_handlers: true
  roles:
    - name: jhampson_dbre.home_assistant.harden_os
    - name: jhampson_dbre.home_assistant.os_agent_auto_update
    - name: jhampson_dbre.home_assistant.fail2ban
      vars:
       fail2ban_reverse_proxy_addon_name: addon_85d0901c_nginx_proxy_waf
    - name: jhampson_dbre.home_assistant.install_hacs