---


# tasks file for docker-ce-ansible-role

- name: Remove previous docker installation
  apt:
    name:
      - "docker.io"
      - "docker-engine"
      - "containerd"
    state: absent

- name: Install prerequisite packages
  apt:
    name: 
      - "apt-transport-https"
      - "ca-certificates"
      - "curl"
      - "gnupg-agent"
      - "software-properties-common"
    state: present

- name: Import Docker CE repository gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Set Docker repository to edge
  apt_repository: 
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu hirsute edge"
    state: present
    update_cache: yes
    
- name: Install Docker
  package:
    name: docker-ce
    state: present
  become: true

- name: Enable Docker service on startup
  service:
    name: docker
    state: started
    enabled: yes

- name: add user to docker group
  user:
    name: shawn
    groups: docker
    append: yes
  become: yes
