- name: Install SSH
  apt:
    name:
      - "openssh-server"
    state: present

- name: Allow SSH in UFW
  ufw: rule=allow port=22 proto=tcp

- name: Set firewall default policy
  ufw: state=enabled policy=reject
  become: true